### PR TITLE
added built-in silence_stashes filter

### PR DESCRIPTION
**Pull request by portertech**
This filter/functionality is currently available in Sensu Enterprise http://sensuapp.org/docs/0.17/enterprise-built-in-filters#silencestashes I've reimplemented it to work with Sensu Core. We at HW believe this built-in filter should be available in Sensu Core.

### CODE REVIEW

**Comment by portertech** [comment]
Looks like the JRuby EM reactor does not support the inactivity timeout, also throwing a `NullPointerException`.

**Comment by portertech** [comment]
Blocked on sensu-em (eventmachine) JRuby reactor fixes/features.

**Comment by portertech** [comment]
I've pulled the upstream eventmachine changes into sensu-em. Next step is adding working inactivity and pending timeouts.

**Comment by runningman84** [comment]
any news here? This seems to be an important feature...

**Comment by cwjohnston** [comment]
I believe this PR is superseded by the planned implementation of silencing as a first-class concept. See https://github.com/sensu/sensu/issues/1328

**Comment by portertech** [comment]
@cwjohnston correct, I am closing this PR as built-in silencing supersedes silence stashes :+1:

**Pull request closed without merging**
